### ISSUE TITLE
Does not support last version of jupyterlab

### ISSUE THREAD

**Issue by edurenye** [jupyterlab/jupyterlab-mp4#6]
I tried to install this extension in Jupyter lab 2.2, but it is not supported.

**Comment by nerikosans** [comment]
Same issue for me, with Jupyter lab 2.2.6.

This is the error message shown when I try to install this extension:
```
Conflicting Dependencies:
JupyterLab                        Extension      Package
>=2.2.0 <2.3.0                    >=1.0.0 <2.0.0 @jupyterlab/rendermime-interfaces 
```

I guess the problem is `@jupyterlab/mp4-extension` is dependent on `"@jupyterlab/rendermime-interfaces": "^1.0.0"`, which supports only under Jupyter lab 2.0.0, although the latest release of `@jupyterlab/rendermime-interfaces` is `2.2.0`.

So just upgrading the dependency version might solve the issue. (I have not tried yet)
